### ISSUE TITLE
Bug(Server): Loading client class on server

### ISSUE THREAD

**Issue by NoaHimesaka1873** [DakotaPride/create-framed#15]
```
mc-1  | [14:15:50] [modloading-worker-0/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/RenderType for invalid dist DEDICATED_SERVER
mc-1  | [14:15:50] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: createframed, class net.dakotapride.createframed.CreateFramedMod
mc-1  | java.lang.ExceptionInInitializerError: null
mc-1  |         at net.dakotapride.createframed.registry.CreateFramedBlocks.register(CreateFramedBlocks.java:242) ~[createframed-1.20.1-1.5.1.jar%23404!/:1.5.1] {re:classloading}
mc-1  |         at net.dakotapride.createframed.CreateFramedMod.<init>(CreateFramedMod.java:37) ~[createframed-1.20.1-1.5.1.jar%23404!/:1.5.1] {re:classloading}
mc-1  |         at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
mc-1  |         at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
mc-1  |         at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
mc-1  |         at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
mc-1  |         at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
mc-1  |         at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:75) ~[language-java-47.2.2.jar%23569!/:47.2] {}
mc-1  |         at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[core-47.2.2.jar%23568!/:47.2] {}
mc-1  |         at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
mc-1  |         at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
mc-1  |         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
mc-1  |         at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
mc-1  |         at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
mc-1  |         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
mc-1  |         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}
mc-1  | Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/RenderType for invalid dist DEDICATED_SERVER
mc-1  |         at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[loader-47.2.2.jar%2351!/:47.2] {}
mc-1  |         at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2358!/:?] {}
mc-1  |         at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2358!/:?] {}
mc-1  |         at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2358!/:?] {}
mc-1  |         at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
mc-1  |         at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
mc-1  |         at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
mc-1  |         at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
mc-1  |         at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
mc-1  |         at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
mc-1  |         at net.dakotapride.createframed.registry.CreateFramedWindows.<clinit>(CreateFramedWindows.java:22) ~[createframed-1.20.1-1.5.1.jar%23404!/:1.5.1] {re:classloading}
mc-1  |         ... 16 more
```

**Comment by DakotaPride** [comment]
The issue should be fixed now! Let me know if you come across anything else!
